apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  namespace: {{ .Values.ingress.namespace }}
  annotations:
    ingress.kubernetes.io/use-port-in-redirects: 'true'
    ingress.kubernetes.io/ssl-redirect: 'true'
    kubernetes.io/ingress.class: std-ingress-class
spec:
  rules:
  - host: {{ .Values.ingress.tls.host }}
    http:
      paths:
      - backend:
          serviceName: {{ .Values.ingress.rules.host.serviceName }}
          servicePort: {{ .Values.ingress.rules.host.servicePort }}
  tls:
  - hosts:
    - {{ .Values.ingress.tls.host }}
